version: '3'

services:
  nodeserver:
    image: nodejs
    build: .
      #context: ./got
    depends_on:
      - db
    ports:
      - "5005:5000"
  db:
    image: postgres:9.5
    restart: always
    ports:
        - '4321:5432'
    environment:
        POSTGRES_PASSWORD: '123456'
        POSTGRES_USER: 'postgres'
        POSTGRES_DB: 'got'
    volumes:
        - ./dados_postgres:/var/lib/postgres/data
  nginx:
    image: nginx
    restart: always 
    build:
      context: ./nginx
    ports:
      - "80:80" 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf